[server]
bind = "127.0.0.1:8848"
stdio_server = false
auth_bearer = ""
allow_origins = ["http://localhost"]

[database]
path = "sqlite://mcp-router.db"

[upstreams.fs]
kind = "stdio"
command = "./target/release/mcp-fs"
args = ["--root", "./"]

[upstreams.web]
kind = "stdio"
command = "./target/release/mcp-webfetch"
args = []

[upstreams.ollama]
kind = "http"
url = "http://127.0.0.1:11434/mcp"
bearer = ""
